name: Python Package (Conda)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        environment-file: environment.yml # Assurez-vous d'avoir un fichier environment.yml dans votre repo
        activate-environment: test-env

    - name: Install dependencies
      run: |
        conda install --yes pytest flake8

    - name: Run tests
      run: |
        pytest tests/

    - name: Lint code
      run: |
        flake8 .
